Repository 6-CSE/HelloWorld, pull requests merged in 2022-10, with the labels that each got.

#220 Added Scratch "Hello World" program
  Scratch/HelloWorld_Guide.md
  Scratch/Scratch Project.sb3
Labels: review-required

#231 Bhailang docs
  Bhailang/README.md
Labels: hacktoberfest-accepted

#232 First Program
  Bhailang/HelloWorld.bhai
Labels: hacktoberfest-accepted

#237 Clojurescript added
  Clojurescript/hello_world.cljx
Labels: hacktoberfest-accepted

#266 Created Hello_world_prime_count.cpp
  C++/Hello_world_prime_count.cpp
Labels: hacktoberfest-accepted

#260 Add files via upload
  Python/hello_world-22.py
Labels: hacktoberfest-accepted

#259 Hello-world file addition
  C/Hello_world_H22.c
Labels: hacktoberfest-accepted

#258 Update README.md
  Bhailang/README.md
Labels: hacktoberfest-accepted

#257 Update HelloWorld.sol
  Solidity/HelloWorld.sol
Labels: hacktoberfest-accepted

#255 Python commit for colored hello world
  Python/hello_world_colored_function.py
  README.md
Labels: hacktoberfest-accepted

#253 Create hello_world.stk
  Stuck/hello_world.stk
Labels: hacktoberfest-accepted

#236 Bhailang
  Bhailang/helloWorld.bhai
Labels: hacktoberfest-accepted

#269 Hello_World_
  Python/Hello_World_H22.py
Labels: hacktoberfest-accepted

#270 Create Hello World.rkt
  Racket/Hello World.rkt
Labels: hacktoberfest-accepted

#251 hello_world
  C++/Hello_World_10.cpp
Labels: hacktoberfest-accepted

#248 Simple hello world using graphical user interface
  Python/gui helloworld.py
Labels: hacktoberfest-accepted

#246 Create hello_world.hack
  Hack/HelloWorld.hack
Labels: hacktoberfest-accepted

#211 files add
  PHP/HelloWorld.php
Labels: hacktoberfest-accepted

#244 Create ReverseHelloWorld.c
  C/ReverseHelloWorld.c
Labels: hacktoberfest-accepted

#242 Hello world accelerator321
  Python/Hello_world_10_lines.py
Labels: hacktoberfest-accepted

#241 Hello world in python using format
  Python/HelloWorld_format.py
Labels: hacktoberfest-accepted

#252 added hello world python program
  Python/Hello_World_Program.py
Labels: hacktoberfest-accepted

#278 Created hello_world_func.cpp
  C++/hello_world_func.cpp
Labels: hacktoberfest-accepted

#281 HelloWorld in PostScript language
  PostScript/Hello_World.ps
Labels: changes-required
